### PR TITLE
Allow ambiguous (degenerate) nucleotide sequence to known amino acids if determinate

### PR DESCRIPTION
**Pull request by tomoakin**
In current implementation, NA#translate will translate to unknown amino acid if the codon contains any degenerate / ambiguity code of nucleotide. However, there are specific patterns of nucleotide sequence such that some nucleotide of the codon are ambiguous but still a specific amino acid / stop codon is specified unambiguously.
To allow such conversion, extended ambiguity aware translation table can be constructed from the standard fully determinate codon table.
Althoug, for standard tables precomputed table might be preferred for speed, just a dynamic table construction is presented here.

### CODE REVIEW

**Comment by ngoto** [comment]
Interesting.
How about performance regression?

**Comment by tomoakin** [comment]
The performance:
The environment required 38 ms for invoking bioruby and create a short na sequence.
2 ms increases to 22 ms for a single translation of the sequence.
another 999 invocations are 4.2 ms in both that do not differ.

Note, with this test 1000.times {puts seq.translate()} is very expensive.
That is because self.[](i) would always call new and run the calculation every time.
Is there a good way to implicitly cache the resulting table?

The actual test results follows.

testing translation with patched codontable.rb
Thu May 31 16:55:19 JST 2018
testing just the frame; 100 invocation of no_trans.rb
no_trans.rb
#!/bin/env ruby
require 'bio'
seq=Bio::Sequence::NA.new("acgtacgtag")
puts seq

real    0m3.812s
user    0m3.246s
sys     0m0.512s
Thu May 31 16:55:23 JST 2018
testing 1 translation
simple_trans.rb
#!/bin/env ruby
require 'bio'
seq=Bio::Sequence::NA.new("acgtactar")
puts seq.translate

real    0m4.023s
user    0m3.430s
sys     0m0.537s
Thu May 31 16:55:27 JST 2018
testing 1000 translation
many_trans.rb
#!/bin/env ruby
require 'bio'
seq=Bio::Sequence::NA.new("acgtactar")
ct = Bio::CodonTable[1]
1000.times {
  puts seq.translate(1,ct)
}

real    0m4.460s
user    0m3.905s
sys     0m0.530s
Thu May 31 16:55:31 JST 2018
testing translation with patched codontable.rb
Thu May 31 16:55:31 JST 2018
testing just the frame; 100 invocation of no_trans.rb
no_trans.rb

real    0m3.816s
user    0m3.236s
sys     0m0.529s
Thu May 31 16:55:35 JST 2018
testing 1 translation
simple_trans.rb

real    0m5.995s
user    0m5.415s
sys     0m0.541s
Thu May 31 16:55:41 JST 2018
testing 1000 translation
many_trans.rb

real    0m6.417s
user    0m5.823s
sys     0m0.558s
Thu May 31 16:55:47 JST 2018

$ cat perf-test.sh 
#!/bin/bash
cp -p codontable.rb $HOME/lcl/lib/ruby/gems/2.4.0/gems/bio-1.5.1/lib/bio/data/
echo testing translation with patched codontable.rb
date
echo testing just the frame\; 100 invocation of no_trans.rb
echo no_trans.rb
cat no_trans.rb
time (for i in `seq 1 100`; do ruby no_trans.rb >/dev/null ; done)
date
echo testing 1 translation 
echo simple_trans.rb
cat simple_trans.rb
time (for i in `seq 1 100`; do ruby simple_trans.rb >/dev/null ; done)
date
echo testing 1000 translation
echo many_trans.rb
cat many_trans.rb
time (for i in `seq 1 100`; do ruby many_trans.rb >/dev/null ; done)
date
echo testing translation with patched codontable.rb
cp -p $HOME/bioruby/lib/bio/data/codontable.rb ~/lcl/lib/ruby/gems/2.4.0/gems/bio-1.5.1/lib/bio/data/
date
echo testing just the frame\; 100 invocation of no_trans.rb
echo no_trans.rb
time (for i in `seq 1 100`; do ruby no_trans.rb >/dev/null ; done)
date
echo testing 1 translation 
echo simple_trans.rb
time (for i in `seq 1 100`; do ruby simple_trans.rb >/dev/null ; done)
date
echo testing 1000 translation
echo many_trans.rb
time (for i in `seq 1 100`; do ruby many_trans.rb >/dev/null ; done)
date
echo copyback the original
cp -p codontable.rb $HOME/lcl/lib/ruby/gems/2.4.0/gems/bio-1.5.1/lib/bio/data/

**Comment by tomoakin** [comment]
please see #122 because the base was changed to exclude unnecessary commits.

**Comment by ngoto** [comment]
closed because new PR #122 is merged

**Pull request closed without merging**
